#!/bin/sh

failed=''

for f in case-*.sys
do
	case="`echo \"$f\" | sed -e 's/^case-//; s/\.sys$//'`"
	if ./r1test $case
	then
		:
	else
		echo
		failed="$failed $case"
		echo
	fi
done

if [ "x$failed" = x ]
then
	echo "
all tests passed."
	exit 0
fi

echo >&2 "
AT LEAST ONE TEST FAILED
$failed
"

exit 1
