#!/bin/sh
# usage: m1test <name> <initfile> <queryargs>

set -e
case="case-$1"; shift
initfile="$1"; shift
queryargs="$*"

initstring="`cat init-$initfile.text`"

echo "$initfile" >"$case.sys"
echo "$queryargs" >>"$case.sys"

echo running "hrecord /... $queryargs"
set +e
ADNS_TEST_OUT_FD=3 3>>"$case.sys" >"$case.stdout" 2>"$case.stderr" </dev/null \
 ./hrecord "/$initstring" $queryargs
rc=$?
set -e

egrep . -- "$case.stderr" "$case.stdout"
echo "exit status: $rc"

if test $rc = 0
then
	echo "test created ok"
fi

exit $rc
